spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: liqing
    password: Liqing1210$
    url: jdbc:mysql://47.107.40.120/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

server:
  context-path: /sell
  #url的前缀